resource rb-iseq
resource rb-value
type errno = s32

ruby-show-version: function()
ruby-init: function()
ruby-options: function(args: list<string>) -> rb-iseq
ruby-script: function(name: string)
ruby-init-loadpath: function()
rb-eval-string-protect: function(str: string) -> tuple<rb-value, s32>
