resource rb-iseq
resource rb-value
type errno = s32

ruby-init: function()
ruby-options: function(args: list<string>) -> rb-iseq
ruby-run-node: function(node: rb-iseq) -> errno
ruby-script: function(name: string)
ruby-init-loadpath: function()
rb-eval-string: function(str: string) -> rb-value
