resource js-abi-value

eval-js: function(code: string) -> js-abi-value
is-js: function(value: js-abi-value) -> bool
instance-of: function(value: js-abi-value, klass: js-abi-value) -> bool
global-this: function() -> js-abi-value
int-to-js-number: function(value: s32) -> js-abi-value
string-to-js-string: function(value: string) -> js-abi-value
bool-to-js-bool: function(value: bool) -> js-abi-value
rb-object-to-js-rb-value: function(raw-rb-abi-value: u32) -> js-abi-value

js-value-to-string: function(value: js-abi-value) -> string

export-js-value-to-host: function(value: js-abi-value)
import-js-value-from-host: function() -> js-abi-value

js-value-typeof: function(value: js-abi-value) -> string

js-value-equal: function(lhs: js-abi-value, rhs: js-abi-value) -> bool
js-value-strictly-equal: function(lhs: js-abi-value, rhs: js-abi-value) -> bool

reflect-apply: function(target: js-abi-value, this-argument: js-abi-value, arguments: list<js-abi-value>) -> js-abi-value
reflect-construct: function(target: js-abi-value, arguments: list<js-abi-value>) -> js-abi-value
reflect-delete-property: function(target: js-abi-value, property-key: string) -> bool
reflect-get: function(target: js-abi-value, property-key: string) -> js-abi-value
reflect-get-own-property-descriptor: function(target: js-abi-value, property-key: string) -> js-abi-value
reflect-get-prototype-of: function(target: js-abi-value) -> js-abi-value
reflect-has: function(target: js-abi-value, property-key: string) -> bool
reflect-is-extensible: function(target: js-abi-value) -> bool
reflect-own-keys: function(target: js-abi-value) -> list<js-abi-value>
reflect-prevent-extensions: function(target: js-abi-value) -> bool
reflect-set: function(target: js-abi-value, property-key: string, value: js-abi-value) -> bool
reflect-set-prototype-of: function(target: js-abi-value, prototype: js-abi-value) -> bool
