// Generated by `wit-bindgen` 0.24.0. DO NOT EDIT!
#ifndef __BINDINGS_EXT_H
#define __BINDINGS_EXT_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>

typedef struct ext_string_t {
  uint8_t*ptr;
  size_t len;
} ext_string_t;

typedef struct ruby_js_js_runtime_own_js_abi_value_t {
  int32_t __handle;
} ruby_js_js_runtime_own_js_abi_value_t;

typedef struct ruby_js_js_runtime_borrow_js_abi_value_t {
  int32_t __handle;
} ruby_js_js_runtime_borrow_js_abi_value_t;

typedef struct ruby_js_js_runtime_js_abi_result_t {
  uint8_t tag;
  union {
    ruby_js_js_runtime_own_js_abi_value_t     success;
    ruby_js_js_runtime_own_js_abi_value_t     failure;
  } val;
} ruby_js_js_runtime_js_abi_result_t;

#define RUBY_JS_JS_RUNTIME_JS_ABI_RESULT_SUCCESS 0
#define RUBY_JS_JS_RUNTIME_JS_ABI_RESULT_FAILURE 1

typedef struct ruby_js_js_runtime_raw_integer_t {
  uint8_t tag;
  union {
    double     as_float;
    ext_string_t     bignum;
  } val;
} ruby_js_js_runtime_raw_integer_t;

#define RUBY_JS_JS_RUNTIME_RAW_INTEGER_AS_FLOAT 0
#define RUBY_JS_JS_RUNTIME_RAW_INTEGER_BIGNUM 1

typedef struct ruby_js_js_runtime_list_borrow_js_abi_value_t {
  ruby_js_js_runtime_borrow_js_abi_value_t *ptr;
  size_t len;
} ruby_js_js_runtime_list_borrow_js_abi_value_t;

typedef struct exports_ruby_js_ruby_runtime_own_rb_iseq_t {
  int32_t __handle;
} exports_ruby_js_ruby_runtime_own_rb_iseq_t;

typedef struct exports_ruby_js_ruby_runtime_rb_iseq_t exports_ruby_js_ruby_runtime_rb_iseq_t;

typedef exports_ruby_js_ruby_runtime_rb_iseq_t* exports_ruby_js_ruby_runtime_borrow_rb_iseq_t;

typedef struct exports_ruby_js_ruby_runtime_own_rb_abi_value_t {
  int32_t __handle;
} exports_ruby_js_ruby_runtime_own_rb_abi_value_t;

typedef struct exports_ruby_js_ruby_runtime_rb_abi_value_t exports_ruby_js_ruby_runtime_rb_abi_value_t;

typedef exports_ruby_js_ruby_runtime_rb_abi_value_t* exports_ruby_js_ruby_runtime_borrow_rb_abi_value_t;

typedef int32_t exports_ruby_js_ruby_runtime_rb_errno_t;

typedef uint32_t exports_ruby_js_ruby_runtime_rb_id_t;

typedef struct ext_list_string_t {
  ext_string_t *ptr;
  size_t len;
} ext_list_string_t;

typedef struct exports_ruby_js_ruby_runtime_tuple2_own_rb_abi_value_s32_t {
  exports_ruby_js_ruby_runtime_own_rb_abi_value_t f0;
  int32_t f1;
} exports_ruby_js_ruby_runtime_tuple2_own_rb_abi_value_s32_t;

typedef struct exports_ruby_js_ruby_runtime_list_borrow_rb_abi_value_t {
  exports_ruby_js_ruby_runtime_borrow_rb_abi_value_t *ptr;
  size_t len;
} exports_ruby_js_ruby_runtime_list_borrow_rb_abi_value_t;

// Imported Functions from `ruby:js/js-runtime`
extern void ruby_js_js_runtime_eval_js(ext_string_t *code, ruby_js_js_runtime_js_abi_result_t *ret);
extern bool ruby_js_js_runtime_is_js(ruby_js_js_runtime_borrow_js_abi_value_t value);
extern bool ruby_js_js_runtime_instance_of(ruby_js_js_runtime_borrow_js_abi_value_t value, ruby_js_js_runtime_borrow_js_abi_value_t klass);
extern ruby_js_js_runtime_own_js_abi_value_t ruby_js_js_runtime_global_this(void);
extern ruby_js_js_runtime_own_js_abi_value_t ruby_js_js_runtime_int_to_js_number(int32_t value);
extern ruby_js_js_runtime_own_js_abi_value_t ruby_js_js_runtime_float_to_js_number(double value);
extern ruby_js_js_runtime_own_js_abi_value_t ruby_js_js_runtime_string_to_js_string(ext_string_t *value);
extern ruby_js_js_runtime_own_js_abi_value_t ruby_js_js_runtime_bool_to_js_bool(bool value);
extern ruby_js_js_runtime_own_js_abi_value_t ruby_js_js_runtime_proc_to_js_function(void);
extern ruby_js_js_runtime_own_js_abi_value_t ruby_js_js_runtime_rb_object_to_js_rb_value(void);
extern void ruby_js_js_runtime_js_value_to_string(ruby_js_js_runtime_borrow_js_abi_value_t value, ext_string_t *ret);
extern void ruby_js_js_runtime_js_value_to_integer(ruby_js_js_runtime_borrow_js_abi_value_t value, ruby_js_js_runtime_raw_integer_t *ret);
extern void ruby_js_js_runtime_export_js_value_to_host(ruby_js_js_runtime_borrow_js_abi_value_t value);
extern ruby_js_js_runtime_own_js_abi_value_t ruby_js_js_runtime_import_js_value_from_host(void);
extern void ruby_js_js_runtime_js_value_typeof(ruby_js_js_runtime_borrow_js_abi_value_t value, ext_string_t *ret);
extern bool ruby_js_js_runtime_js_value_equal(ruby_js_js_runtime_borrow_js_abi_value_t lhs, ruby_js_js_runtime_borrow_js_abi_value_t rhs);
extern bool ruby_js_js_runtime_js_value_strictly_equal(ruby_js_js_runtime_borrow_js_abi_value_t lhs, ruby_js_js_runtime_borrow_js_abi_value_t rhs);
extern void ruby_js_js_runtime_reflect_apply(ruby_js_js_runtime_borrow_js_abi_value_t target, ruby_js_js_runtime_borrow_js_abi_value_t this_argument, ruby_js_js_runtime_list_borrow_js_abi_value_t *arguments, ruby_js_js_runtime_js_abi_result_t *ret);
extern void ruby_js_js_runtime_reflect_get(ruby_js_js_runtime_borrow_js_abi_value_t target, ext_string_t *property_key, ruby_js_js_runtime_js_abi_result_t *ret);
extern void ruby_js_js_runtime_reflect_set(ruby_js_js_runtime_borrow_js_abi_value_t target, ext_string_t *property_key, ruby_js_js_runtime_borrow_js_abi_value_t value, ruby_js_js_runtime_js_abi_result_t *ret);
extern void ruby_js_js_runtime_throw_prohibit_rewind_exception(ext_string_t *message);

// Exported Functions from `ruby:js/ruby-runtime`
void exports_ruby_js_ruby_runtime_ruby_show_version(void);
void exports_ruby_js_ruby_runtime_ruby_init(void);
void exports_ruby_js_ruby_runtime_ruby_sysinit(ext_list_string_t *args);
exports_ruby_js_ruby_runtime_own_rb_iseq_t exports_ruby_js_ruby_runtime_ruby_options(ext_list_string_t *args);
void exports_ruby_js_ruby_runtime_ruby_script(ext_string_t *name);
void exports_ruby_js_ruby_runtime_ruby_init_loadpath(void);
void exports_ruby_js_ruby_runtime_rb_eval_string_protect(ext_string_t *str, exports_ruby_js_ruby_runtime_tuple2_own_rb_abi_value_s32_t *ret);
void exports_ruby_js_ruby_runtime_rb_funcallv_protect(exports_ruby_js_ruby_runtime_borrow_rb_abi_value_t recv, exports_ruby_js_ruby_runtime_rb_id_t mid, exports_ruby_js_ruby_runtime_list_borrow_rb_abi_value_t *args, exports_ruby_js_ruby_runtime_tuple2_own_rb_abi_value_s32_t *ret);
exports_ruby_js_ruby_runtime_rb_id_t exports_ruby_js_ruby_runtime_rb_intern(ext_string_t *name);
exports_ruby_js_ruby_runtime_own_rb_abi_value_t exports_ruby_js_ruby_runtime_rb_errinfo(void);
void exports_ruby_js_ruby_runtime_rb_clear_errinfo(void);
void exports_ruby_js_ruby_runtime_rstring_ptr(exports_ruby_js_ruby_runtime_borrow_rb_abi_value_t value, ext_string_t *ret);
void exports_ruby_js_ruby_runtime_rb_vm_bugreport(void);
bool exports_ruby_js_ruby_runtime_rb_gc_enable(void);
bool exports_ruby_js_ruby_runtime_rb_gc_disable(void);
bool exports_ruby_js_ruby_runtime_rb_set_should_prohibit_rewind(bool new_value);
exports_ruby_js_ruby_runtime_own_rb_abi_value_t exports_ruby_js_ruby_runtime_export_rb_value_to_js(void);

// Helper Functions

extern void ruby_js_js_runtime_js_abi_value_drop_own(ruby_js_js_runtime_own_js_abi_value_t handle);

extern ruby_js_js_runtime_borrow_js_abi_value_t ruby_js_js_runtime_borrow_js_abi_value(ruby_js_js_runtime_own_js_abi_value_t handle);

void ruby_js_js_runtime_js_abi_result_free(ruby_js_js_runtime_js_abi_result_t *ptr);

void ruby_js_js_runtime_raw_integer_free(ruby_js_js_runtime_raw_integer_t *ptr);

void ruby_js_js_runtime_list_borrow_js_abi_value_free(ruby_js_js_runtime_list_borrow_js_abi_value_t *ptr);

extern void exports_ruby_js_ruby_runtime_rb_iseq_drop_own(exports_ruby_js_ruby_runtime_own_rb_iseq_t handle);

extern exports_ruby_js_ruby_runtime_own_rb_iseq_t exports_ruby_js_ruby_runtime_rb_iseq_new(exports_ruby_js_ruby_runtime_rb_iseq_t *rep);
extern exports_ruby_js_ruby_runtime_rb_iseq_t* exports_ruby_js_ruby_runtime_rb_iseq_rep(exports_ruby_js_ruby_runtime_own_rb_iseq_t handle);
void exports_ruby_js_ruby_runtime_rb_iseq_destructor(exports_ruby_js_ruby_runtime_rb_iseq_t *rep);

extern void exports_ruby_js_ruby_runtime_rb_abi_value_drop_own(exports_ruby_js_ruby_runtime_own_rb_abi_value_t handle);

extern exports_ruby_js_ruby_runtime_own_rb_abi_value_t exports_ruby_js_ruby_runtime_rb_abi_value_new(exports_ruby_js_ruby_runtime_rb_abi_value_t *rep);
extern exports_ruby_js_ruby_runtime_rb_abi_value_t* exports_ruby_js_ruby_runtime_rb_abi_value_rep(exports_ruby_js_ruby_runtime_own_rb_abi_value_t handle);
void exports_ruby_js_ruby_runtime_rb_abi_value_destructor(exports_ruby_js_ruby_runtime_rb_abi_value_t *rep);

void ext_list_string_free(ext_list_string_t *ptr);

void exports_ruby_js_ruby_runtime_list_borrow_rb_abi_value_free(exports_ruby_js_ruby_runtime_list_borrow_rb_abi_value_t *ptr);

// Transfers ownership of `s` into the string `ret`
void ext_string_set(ext_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void ext_string_dup(ext_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void ext_string_free(ext_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
