resource rb-iseq
resource rb-abi-value
type rb-errno = s32
type rb-id = u32

ruby-show-version: function()
ruby-init: function()
ruby-sysinit: function(args: list<string>)
ruby-options: function(args: list<string>) -> rb-iseq
ruby-script: function(name: string)
ruby-init-loadpath: function()
rb-eval-string-protect: function(str: string) -> tuple<rb-abi-value, s32>
rb-funcallv-protect: function(recv: rb-abi-value, mid: rb-id, args: list<rb-abi-value>) -> tuple<rb-abi-value, s32>
rb-intern: function(name: string) -> rb-id
rb-errinfo: function() -> rb-abi-value

rstring-ptr: function(value: rb-abi-value) -> string
