[package]
name = "ruby_wasm"
version = "0.0.0"
edition = "2021"
authors = ["Yuta Saito <kateinoigakukun@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2", features = ["bytes"] }
bytes = "1"
wizer = "4.0.0"
wasi-vfs-cli = { git = "https://github.com/kateinoigakukun/wasi-vfs/", tag = "0.5.2" }
structopt = "0.3.26"
wit-component = "0.203.0"
