name: Build gems
on:
  push:
    branches: [main]
    tags: ["*"]
    paths-ignore:
      - "*.md"
      - "docs/**"
  pull_request:

jobs:
  ci-data:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.fetch.outputs.result }}
    steps:
      - uses: oxidize-rb/actions/fetch-ci-data@v1
        id: fetch
        with:
          supported-ruby-platforms: |
            exclude: [arm-linux, x64-mingw32]
          stable-ruby-versions: |
            exclude: [head]

  cross-gem:
    name: Compile native gem for ${{ matrix.ruby-platform }}
    runs-on: ubuntu-latest
    needs: ci-data
    strategy:
      fail-fast: false
      matrix:
        ruby-platform: ${{ fromJSON(needs.ci-data.outputs.result).supported-ruby-platforms }}
    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"

      - uses: oxidize-rb/actions/cross-gem@v1
        id: cross-gem
        with:
          platform: ${{ matrix.ruby-platform }}
          ruby-versions: ${{ join(fromJSON(needs.ci-data.outputs.result).stable-ruby-versions, ',') }}

      - uses: actions/upload-artifact@v5
        with:
          name: cross-gem-${{ matrix.ruby-platform }}
          path: ${{ steps.cross-gem.outputs.gem-path }}
          if-no-files-found: error
